# Web Scraping Assignment No 4

# Importing important packages.

In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
import time

# Q.1)Scrape the details of most viewed videos on YouTube from Wikipedia:

Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/

You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

# Connecting with chrome webdriver and putting the website url.

In [136]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

# Creating the empty lists for attributes of resultant dataset.

In [137]:
rank=[]
name=[]
artist=[]
upload_date=[]
views=[]

# Extracting data from website and putting into the empty lists that we have created already.

In [138]:
rows=driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr')

In [139]:
rank=[]
for i in rows:
    rank.append(i.text)

In [140]:
rank=rank[0:30]

In [210]:
#Creating a empty list rank and adding data into it by using for loop.
ranks=[]
for i in range(1,31):
    ra=driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i)+']/td[1]')
    ranks.append(ra)
    
rank=[]
for i in range(0,30):
    rank.append(ranks[i][0].text)

In [211]:
#Creating a empty list name and adding data into it by using for loop.
name=[]
names=[]
for i in range(1,31):
    na=driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i)+']/td[2]')
    name.append(na)

In [212]:
for i in range(0,30):
        names.append(name[i][0].text)

In [214]:
naam=[]
for i in names:
    naam.append(i.split("[")[0])

In [216]:
naav=[]
for i in naam:
    naav.append(i.replace('"', ' '))

In [217]:
naa=[]
for i in naav:
    naa.append(i.replace(" ",''))

In [219]:
#Creating a empty list artists and adding data into it by using for loop.
artist=[]
for i in range(1,31):
    na=driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i)+']/td[3]')
    artist.append(na)

In [220]:
artists=[]
for i in range(0,30):
        artists.append(artist[i][0].text)

In [221]:
#Creating a empty list upload_date and adding data into it by using for loop.
upload=[]
for i in range(1,31):
    na=driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i)+']/td[5]')
    upload.append(na)

In [222]:
upload_date=[]
for i in range(0,30):
        upload_date.append(upload[i][0].text)

In [223]:
#Creating a empty list view and adding data into it by using for loop.
view=[]
for i in range(1,31):
    na=driver.find_elements_by_xpath('//*[@id="mw-content-text"]/div[1]/table[3]/tbody/tr['+str(i)+']/td[4]')
    view.append(na)

In [224]:
views=[]
for i in range(0,30):
        views.append(view[i][0].text)

# Creating our final dataframe with the help of the lists which we have created.

In [225]:
df_wiki=pd.DataFrame({"Rank":rank,"Name":naa,"Artist":artists,"Upload date":upload_date,"Views":views})

In [226]:
df_wiki

,Rank,Name,Artist,Upload date,Views
0,1.,BabySharkDance,Pinkfong Kids' Songs & Stories,"June 17, 2016",9.27
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.52
2,3.,JohnyJohnyYesPapa,LooLoo Kids,"October 8, 2016",5.68
3,4.,ShapeofYou,Ed Sheeran,"January 30, 2017",5.45
4,5.,SeeYouAgain,Wiz Khalifa,"April 6, 2015",5.25
5,6.,BathSong,Cocomelon – Nursery Rhymes,"May 2, 2018",4.49
6,7.,LearningColors–ColorfulEggsonaFarm,Miroshka TV,"February 27, 2018",4.46
7,8.,MashaandtheBear–RecipeforDisaster,Get Movies,"January 31, 2012",4.46
8,9.,UptownFunk,Mark Ronson,"November 19, 2014",4.28
9,10.,GangnamStyle,Psy,"July 15, 2012",4.18
10,11.,PhonicsSongwithTwoWords,ChuChu TV,"March 6, 2014",4.14
11,12.,DameTuCosita,El Chombo,"April 5, 2018",3.57
12,13.,Sugar,Maroon 5,"January 14, 2015",3.54
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.46
14,15.,Roar,Katy Perry,"September 5, 2013",3.42
15,16.,CountingStars,OneRepublic,"May 31, 2013",3.38
16,17.,ThinkingOutLoud,Ed Sheeran,"October 7, 2014",3.31
17,18.,WheelsontheBus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.24
18,19.,DarkHorse,Katy Perry,"February 20, 2014",3.14
19,20.,Faded,Alan Walker,"December 3, 2015",3.13
20,21.,GirlsLikeYou,Maroon 5,"May 31, 2018",3.11
21,22.,ShakeItOff,Taylor Swift,"August 18, 2014",3.09
22,23.,LeanOn,Major Lazer,"March 22, 2015",3.09
23,24.,Bailando,Enrique Iglesias,"April 11, 2014",3.09
24,25.,LetHerGo,Passenger,"July 25, 2012",3.07
25,26.,AxelF,Crazy Frog,"June 16, 2009",2.98
26,27.,MiGente,J Balvin,"June 29, 2017",2.97
27,28.,Perfect,Ed Sheeran,"November 9, 2017",2.94
28,29.,WakaWaka(ThisTimeforAfrica),Shakira,"June 4, 2010",2.93
29,30.,Hello,Adele,"October 22, 2015",2.88

# Q2.) Scrape the details team India’s international fixtures from bcci.tv.

Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

# Connecting with chrome webdriver and feeding the website.

In [244]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://www.bcci.tv/."
driver.get(url)

# Creating empty lists and using xpath methods to extract the data from website into the list

In [246]:
intern_fix=driver.find_element_by_xpath('//a[@class="navigation__link navigation__link--in-drop-down"]')
intern_fix.click()

In [254]:
title=[]
series=[]
place=[]
time=[]

In [248]:
titl=driver.find_elements_by_xpath('//p[@class="fixture__additional-info"]')

In [259]:
title=[]
for i in titl:
    title.append(i.text.split(",")[0])

In [261]:
place=[]
for i in titl:
    place.append(i.text.split(",")[1])

In [263]:
series=driver.find_elements_by_xpath('//span[@class="u-unskewed-text fixture__tournament-label u-truncated"]')

In [264]:
ser=[]
for i in series:
    ser.append(i.text)

In [271]:
dandt=driver.find_elements_by_xpath('//span[@class="fixture__datetime tablet-only"]')
date=[]
time=[]
for i in dandt:
    date.append(i.text.split(" ")[0:3])
    time.append(i.text.split(" ")[3:])

# Creating the final dataframe with the help of lists.

In [278]:
df_bcci=pd.DataFrame({"Title":title,"Series":ser,"Place":place,"Date":date,"Time":time})

In [279]:
df_bcci

,Title,Series,Place,Date,Time
0,4th Test The Oval,ENGLAND V INDIA 2021,London,"[Thursday, 2, September]","[15:30, IST]"
1,5th Test Old Trafford,ENGLAND V INDIA 2021,Manchester,"[Friday, 10, September]","[15:30, IST]"
2,Match 16 Dubai International Cricket Stadium,2021 ICC MEN'S T20 WORLD CUP,Dubai,"[Sunday, 24, October]","[19:30, IST]"
3,Match 28 Dubai International Cricket Stadium,2021 ICC MEN'S T20 WORLD CUP,Dubai,"[Sunday, 31, October]","[19:30, IST]"
4,Match 33 Sheikh Zayed Cricket Stadium,2021 ICC MEN'S T20 WORLD CUP,Abu Dhabi,"[Wednesday, 3, November]","[19:30, IST]"
5,Match 37 Dubai International Cricket Stadium,2021 ICC MEN'S T20 WORLD CUP,Dubai,"[Friday, 5, November]","[19:30, IST]"
6,Match 42 Dubai International Cricket Stadium,2021 ICC MEN'S T20 WORLD CUP,Dubai,"[Monday, 8, November]","[19:30, IST]"

# Q.3)Scrape the details of selenium exception from guru99.com.

Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code.

# Calling the webdriver and putting the website url.

In [286]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://www.guru99.com/"
driver.get(url)

# Collecting the information from the website and storing in the form of list by xpath.

In [287]:
selenium=driver.find_element_by_xpath('//a[@title="Selenium"]').click()

In [288]:
selenium_exp=driver.find_element_by_xpath('//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()

In [289]:
details=driver.find_elements_by_xpath('//tbody//tr')

# Using for loops to add the data into the empty list which we have created for each attribute.

In [292]:
detail=[]
for i in details:
    detail.append(i.text)

In [295]:
detail=detail[1:]

In [297]:
exception=[]
for i in detail:
    exception.append(i.split(" ")[0])

In [299]:
len(exception)

41

In [302]:
description=[]
for i in detail:
    description.append(i.split(" ")[1:])

In [304]:
desc=[]
for i in description:
    desc.append(' '.join(i))

# Creating the final dataframe with the help of the lists.

In [307]:
df_99=pd.DataFrame({"Exception Name":exception,"Description":desc})

In [308]:
df_99

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

# Q.4)Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP at current price (19-20)

D) GSDP at current price (18-19)

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

# Calling the webdriver and putting in the url.

In [263]:
driver=webdriver.Chrome("chromedriver.exe")
url="http://statisticstimes.com/"
driver.get(url)

In [230]:
indian_states=WebDriverWait(driver,12).until(EC.element_to_be_clickable((By.XPATH,'//*[@id="top"]/div[2]/div[3]/button'))).click()

In [238]:
states=WebDriverWait(driver,12).until(EC.element_to_be_clickable((By.LINK_TEXT,'India'))).click()

TimeoutException: Message:

In [240]:
gdp_states=WebDriverWait(driver,12).until(EC.element_to_be_clickable((By.XPATH,'//a[@class="ec"]'))).click()

TimeoutException: Message:

In [264]:
rank=[]
for i in range (1,34):
    ra=driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i)+']/td[1]')
    rank.append(ra.text)

In [267]:
state=[]
for i in range (1,34):
    sa=driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i)+']/td[2]')
    state.append(sa.text)

In [269]:
gsdp_current_18_19=[]
for i in range (1,34):
    sa=driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i)+']/td[4]')
    gsdp_current_18_19.append(sa.text)

In [270]:
gsdp_current_19_20=[]
for i in range (1,34):
    sa=driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i)+']/td[3]')
    gsdp_current_19_20.append(sa.text)

In [271]:
share_18_19=[]
for i in range (1,34):
    sa=driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i)+']/td[5]')
    share_18_19.append(sa.text)

In [272]:
gdp=[]
for i in range (1,34):
    sa=driver.find_element_by_xpath('//*[@id="table_id"]/tbody/tr['+str(i)+']/td[6]')
    gdp.append(sa.text)

# Creating a dataframe with the help of the list

In [274]:
df_gdp=pd.DataFrame({"Rank":rank,"State":state,"GSDP Current 18-19":gsdp_current_18_19,"GSDP Current 19-20":gsdp_current_19_20,"Share 18-19":share_18_19,"GDP":gdp})

In [275]:
df_gdp

,Rank,State,GSDP Current 18-19,GSDP Current 19-20,Share 18-19,GDP
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# Q.5)Scrape the details of trending repositories on Github.com.

Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

# Calling the webdriver and putting in the url.

In [109]:
driver=webdriver.Chrome("chromedriver.exe")
url="http://github.com/"
driver.get(url)

# Creating the empty lists for different attributes and adding the data into it from website by using different selectors.

In [112]:
trending=WebDriverWait(driver,12).until(EC.element_to_be_clickable((By.XPATH,'/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a'))).click()

In [113]:
title=[]
name=driver.find_elements_by_xpath('//span[@class="text-normal"]')

In [114]:
for i in name:
    title.append(i.text.split(" ")[0])

In [116]:
description=driver.find_elements_by_xpath('//p[@class="col-9 color-text-secondary my-1 pr-4"]')

In [117]:
desc=[]
for i in description:
    desc.append(i.text)

In [119]:
lang=driver.find_elements_by_xpath('//span[@itemprop="programmingLanguage"]')

In [120]:
programming_lang=[]
for i in lang:
    programming_lang.append(i.text)

In [132]:
title=title[0:23]

In [133]:
desc=desc[0:23]

# Creating dataframe from the lists.

In [134]:
df_github=pd.DataFrame({"Repository Title":title,"Repository Description":desc,"Programming Language Used":programming_lang})

In [135]:
df_github

,Repository Title,Repository Description,Programming Language Used
0,GTAmodding,"GTA III, Vice City",C++
1,VickScarlet,やり直すんだ。そして、次はうまくやる。,JavaScript
2,lootproject,Loot Project website,TypeScript
3,TheAlgorithms,All Algorithms implemented in Python,Python
4,Anish-Agnihotri,Scripts to collect statistics about LOOT + der...,JavaScript
5,TheAlgorithms,Collection of various algorithms in mathematic...,C++
6,donnemartin,Learn how to design large-scale systems. Prep ...,Python
7,microsoft,Windows system utilities to maximize productivity,C#
8,openwrt,This repository is a mirror of https://git.ope...,C
9,v2fly,A platform for building proxies to bypass netw...,Go
10,MarlinFirmware,Marlin is an optimized firmware for RepRap 3D ...,C++
11,HashLips,Create generative art by using the canvas api ...,JavaScript
12,vxunderground,Collection of malware source code for a variet...,Assembly
13,metaplex-foundation,Protocol and application framework for decentr...,Rust
14,armosec,kubescape is the first tool for testing if Kub...,Go
15,wrfree,freefq账号已恢复！翻墙、免费翻墙、免费科学上网、免费节点、免费梯子、免费ss/v2ra...,TypeScript
16,bespoyasov,React + TypeScript app built using clean archi...,JavaScript
17,TheAlgorithms,A repository for All algorithms implemented in...,JavaScript
18,0voice,【未来服务器端编程语言】最全空降golang资料补给包（满血战斗），包含文章，书籍，作者论文...,Java
19,iptv-org,Collection of publicly available IPTV channels...,JavaScript
20,Anuken,A sandbox tower defense game,JavaScript
21,30-seconds,Short JavaScript code snippets for all your de...,C++
22,NotLuksus,A tool to generate generative NFT art projects.,Python

# Q6.) Scrape the details of top 100 songs on billboard.com.

Url = https://www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board

Note: - From the home page you have to click on the charts option then hot 100-page link through code.

# Calling the webdriver and putting the url .

In [351]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://www.billboard.com/"
driver.get(url)

# Creating empty lists and adding data into it from website using different methods.

In [359]:
chart=driver.find_element_by_xpath('//*[@id="root"]/div[2]/div[2]/header/div/ul/li[1]/a').click()

In [360]:
hot100=driver.find_element_by_xpath('//*[@id="main"]/div[2]/div/div[1]/a/div[2]/div[2]/div[1]').click()

In [361]:
name=[]
names=driver.find_elements_by_xpath('//span[@class="chart-element__information__song text--truncate color--primary"]')
for i in names:
    name.append(i.text)

In [363]:
artist=[]
artist_name=driver.find_elements_by_xpath('//span[@class="chart-element__information__artist text--truncate color--secondary"]')
for i in artist_name:
    artist.append(i.text)

In [365]:
last_week_rank=[]
last_week=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')
for i in last_week:
    last_week_rank.append(i.text)

In [367]:
peak_rank=[]
peak=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--peak"]')
for i in peak:
    peak_rank.append(i.text)

In [369]:
weeks_on_boards=[]
weeks_on=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--week"]')
for i in weeks_on:
    weeks_on_boards.append(i.text)

# Creating final dataframe with the help of lists

In [371]:
df_billboard=pd.DataFrame({"Song Name":name,"Artists":artist,"Last Week Rank":last_week_rank,"Peak Rank":peak_rank,"Weeks on boards":weeks_on_boards})

In [372]:
df_billboard

,Song Name,Artists,Last Week Rank,Peak Rank,Weeks on boards
0,Stay,The Kid LAROI & Justin Bieber,1,1,7
1,Bad Habits,Ed Sheeran,2,2,9
2,Good 4 U,Olivia Rodrigo,3,1,15
3,Kiss Me More,Doja Cat Featuring SZA,5,3,20
4,Industry Baby,Lil Nas X & Jack Harlow,7,2,5
...,...,...,...,...,...
95,Tick Tock,Young Thug,-,96,1
96,Permission To Dance,BTS,66,1,7
97,AM,Nio Garcia X J Balvin X Bad Bunny,85,41,9
98,Time Heals,Rod Wave,-,99,1
99,Thinking 'Bout You,Dustin Lynch Featuring Lauren Alaina Or MacKen...,91,91,2

# Q.7)Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location

Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

# Calling the webdriver and putting the website url into it.

In [276]:
driver=webdriver.Chrome("chromedriver.exe")
url="http://www.naukri.com"
driver.get(url)

In [277]:

recruiters=WebDriverWait(driver,12).until(EC.element_to_be_clickable((By.XPATH,'//a[@title="Search Recruiters"]'))).click()

In [282]:
skill_des=WebDriverWait(driver,15).until(EC.element_to_be_clickable((By.XPATH,'//input[@rel="custom:1016"]')))

TimeoutException: Message:

In [ ]:
skill_des.clear()
skill_des.send_keys("Data Science")

In [291]:
name=[]
for i in range(1,26):
    na=driver.find_element_by_xpath('//*[@id="tabP-1"]/div['+str(i)+']/div[1]/div[1]/div[1]/p/a[1]/span')
    name.append(na)

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="tabP-1"]/div[1]/div[1]/div[1]/div[1]/p/a[1]/span"}
  (Session info: chrome=92.0.4515.159)

# Q.8). Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

# Calling the webdriver and putting the url into it.

In [5]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
driver.get(url)

# Creating empty lists and adding the data into the empty lists by using the xpath methods.

In [13]:
rank=[]
for i in range (0,100):
    ranks=driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-0"]')
    rank.append(ranks.text)

In [16]:
title=[]
for i in range (0,100):
    titl=driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-1"]')
    title.append(titl.text)

In [19]:
author=[]
for i in range (0,100):
    auth=driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-2"]')
    author.append(auth.text)

In [22]:
vol_sal=[]
for i in range (0,100):
    vol=driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-3"]')
    vol_sal.append(vol.text)

In [25]:
publisher=[]
for i in range (0,100):
    pub=driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-4"]')
    publisher.append(pub.text)

In [28]:
genre=[]
for i in range (0,100):
    gen=driver.find_element_by_xpath('//*[@id="table-cell-10943-'+str(i)+'-5"]')
    genre.append(gen.text)

# Creating the final dataframe with the help of our lists.

In [31]:
df_book=pd.DataFrame({"Rank":rank,"Title":title,"Author":author,"Volume Sales":vol_sal,"Publisher":publisher,"Genre":genre})

In [32]:
df_book

,Rank,Title,Author,Volume Sales,Publisher,Genre
0,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
95,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q9.) Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

# Calling the webdriver and putting the url into it.

In [33]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://www.imdb.com/list/ls095964455/"
driver.get(url)

# Creating empty lists and adding the data into the lists from website by using the xpath.

In [37]:
rank=[]
ran=driver.find_elements_by_xpath('//span[@class="lister-item-index unbold text-primary"]')
for i in ran:
    rank.append(i.text)

In [39]:
name=[]
nam=driver.find_elements_by_xpath('//h3[@class="lister-item-header"]//a')
for i in nam:
    name.append(i.text)

In [41]:
year_span=[]
year=driver.find_elements_by_xpath('//span[@class="lister-item-year text-muted unbold"]')
for i in year:
    year_span.append(i.text)

In [43]:
genre=[]
gen=driver.find_elements_by_xpath('//span[@class="genre"]')
for i in gen:
    genre.append(i.text)

In [46]:
runtime=[]
run=driver.find_elements_by_xpath('//span[@class="runtime"]')
for i in run:
    runtime.append(i.text)

In [67]:
ratings=[]
rat=driver.find_elements_by_xpath('//div[@class="ipl-rating-star small"]//span')
for i in rat:
    ratings.append(i.text)
    
ratings=ratings[1::2]

In [50]:
votes=[]
vot=driver.find_elements_by_xpath('//p[@class="text-muted text-small"]//span[@name="nv"]')
for i in vot:
    votes.append(i.text)

# Creating the dataframe by using lists we have created.

In [68]:
df_imdb=pd.DataFrame({"Rank":rank,"Name":name,"Year Span":year_span,"Genre":genre,"Runtime":runtime,"Ratings":ratings,"Votes":votes})

In [69]:
df_imdb

,Rank,Name,Year Span,Genre,Runtime,Ratings,Votes
0,1.,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,867,147"
1,2.,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"902,755"
2,3.,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"894,405"
3,4.,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"269,207"
4,5.,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"229,461"
...,...,...,...,...,...,...,...
95,96.,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"45,477"
96,97.,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"56,352"
97,98.,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"174,323"
98,99.,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"36,480"
99,100.,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"198,155"

# Q.10.) Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/

You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the Show All Dataset page through code.

# Calling the webdriver and putting in the url.

In [70]:
driver=webdriver.Chrome("chromedriver.exe")
url="https://archive.ics.uci.edu/"
driver.get(url)

# Creating empty lists for various attributes of our dataframe and adding the data into the lists from website by using xpath method.

In [78]:
all_dataset=driver.find_element_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a').click()

In [91]:
name=[]
for i in range (2,590):
    nam=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[1]/table/tbody/tr/td[2]/p/b/a')
    for i in nam:
        name.append(i)
        
names=[]
for i in name:
    names.append(i.text)

In [92]:
datatype=[]
for i in range (2,590):
    dat=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[2]/p')
    for i in dat:
        datatype.append(i)
        
datatyps=[]
for i in datatype:
    datatyps.append(i.text)

In [95]:
task=[]
for i in range (2,590):
    ta=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[3]/p')
    for i in ta:
        task.append(i)
        
tasks=[]
for i in task:
    tasks.append(i.text)

In [97]:
attr=[]
for i in range (2,590):
    at=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[4]/p')
    for i in at:
        attr.append(i)
        
attr_typ=[]
for i in attr:
    attr_typ.append(i.text)

In [101]:
num_i=[]
for i in range (2,590):
    num=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[5]/p')
    for i in num:
        num_i.append(i)
        
number_i=[]
for i in num_i:
    number_i.append(i.text)

In [103]:
num_a=[]
for i in range (2,590):
    num=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[6]/p')
    for i in num:
        num_a.append(i)
        
number_a=[]
for i in num_a:
    number_a.append(i.text)

In [105]:
year=[]
for i in range (2,590):
    yea=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr['+str(i)+']/td[7]/p')
    for i in yea:
        year.append(i)
        
years=[]
for i in year:
    years.append(i.text)

# Creating the final dataframe with the help of our lists.

In [107]:
df_uci=pd.DataFrame({"Name":names,"Data Types":datatyps,"Default tasks":tasks,"Attribute Types":attr_typ,"Number of instances":number_i,"Number of attributes":number_a,"Year":years})

In [108]:
df_uci

,Name,Data Types,Default tasks,Attribute Types,Number of instances,Number of attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021